### ISSUE TITLE
Separate Cash Buyers and Private Investors for clarity to target audience

### ISSUE THREAD

**Issue by volhomes** [volhomes/vol-homes#13]
I have marked up a PDF called Investors/Buyers split and put in dropbox which should cover everything

**Comment by volhomes** [comment]
This is perfect… the only comment that I would have is to make the top button say the same as the bottom button on this page http://volhomes.com/cash-buyers

**Comment by daveaseeman** [comment]
Okay cool, glad you like it. I'll do that and I need to separate the lists on the backend and remove the auto responder from cash buyers. But otherwise this one should be checked off the list! 

~~~Dave Seeman

Freelance Web & Product Design

e: daveaseeman.com

p: 615-944-5829

t: @daveaseeman

in: daveaseeman

On Mon, Sep 7, 2015 at 3:34 PM, Cassidy Melhorn notifications@github.com
wrote:

> ## This is perfect… the only comment that I would have is to make the top button say the same as the bottom button on this page http://volhomes.com/cash-buyers
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/volhomes/vol-homes/issues/13#issuecomment-138374126

**Comment by daveaseeman** [comment]
done :+1:
